## 기상조건 표시
- 맑음 / 약한눈비 / 강한눈비(110mm이상, 신적설 5cm이상) / 한파(최저기온 -12이하), 폭염(최고온도 33도 이상)

In [16]:
import pandas as pd
temp_rain_data = pd.read_csv("1_1_[정리]서울_기온_강수량_220701_230820.csv")
temp_rain_data

              날짜  평균기온(℃)  최저기온(℃)  최고기온(℃)  강수량(mm)
0     2022-07-01     26.6     21.9     30.9      0.0
1     2022-07-02     28.8     24.0     33.8      0.0
2     2022-07-03     29.3     24.4     34.2      0.0
3     2022-07-04     29.3     26.4     32.6      0.0
4     2022-07-05     29.2     26.7     33.1      0.0
..           ...      ...      ...      ...      ...
411   2023-08-16     27.3     24.7     31.6      0.3
412   2023-08-17     28.2     24.5     32.4      0.0
413   2023-08-18     29.1     25.5     33.3      0.1
414   2023-08-19     29.1     26.4     33.6      0.0
415   2023-08-20     28.3     25.5     31.8      0.0

[416 rows x 5 columns]

In [17]:
new_values = []
for i in range(len(temp_rain_data)):
    if temp_rain_data['최고기온(℃)'][i] >= 33 or temp_rain_data['최저기온(℃)'][i] <= -12:
        new_values.append("폭염/한파")
    elif temp_rain_data['강수량(mm)'][i] >= 110:
        new_values.append("강한눈비")
    elif temp_rain_data['강수량(mm)'][i] > 0 and temp_rain_data['강수량(mm)'][i] < 110:
        new_values.append("약한눈비")
    elif temp_rain_data['최저기온(℃)'][i] < 11 and temp_rain_data['강수량(mm)'][i] >50:
        new_values.append("강한눈비")
    else:
        new_values.append("맑음")
temp_rain_data['기상조건'] = new_values

print(temp_rain_data)

              날짜  평균기온(℃)  최저기온(℃)  최고기온(℃)  강수량(mm)   기상조건
0     2022-07-01     26.6     21.9     30.9      0.0     맑음
1     2022-07-02     28.8     24.0     33.8      0.0  폭염/한파
2     2022-07-03     29.3     24.4     34.2      0.0  폭염/한파
3     2022-07-04     29.3     26.4     32.6      0.0     맑음
4     2022-07-05     29.2     26.7     33.1      0.0  폭염/한파
..           ...      ...      ...      ...      ...    ...
411   2023-08-16     27.3     24.7     31.6      0.3   약한눈비
412   2023-08-17     28.2     24.5     32.4      0.0     맑음
413   2023-08-18     29.1     25.5     33.3      0.1  폭염/한파
414   2023-08-19     29.1     26.4     33.6      0.0  폭염/한파
415   2023-08-20     28.3     25.5     31.8      0.0     맑음

[416 rows x 6 columns]

In [18]:
# temp_rain_data.to_csv("1_2_기상조건.csv")

## 날짜를 연/월/일로 바꾸기

In [19]:
temp_rain_data['날짜']

0       2022-07-01
1       2022-07-02
2       2022-07-03
3       2022-07-04
4       2022-07-05
          ...
411     2023-08-16
412     2023-08-17
413     2023-08-18
414     2023-08-19
415     2023-08-20
Name: 날짜, Length: 416, dtype: object

In [20]:
import datetime
temp_rain_data['날짜'] = pd.to_datetime(temp_rain_data['날짜'])
temp_rain_data['날짜'].head(1)

0   2022-07-01
Name: 날짜, dtype: datetime64[ns]

In [23]:
temp_rain_data['연'] = temp_rain_data['날짜'].dt.year
temp_rain_data['월'] = temp_rain_data['날짜'].dt.month
temp_rain_data['일'] = temp_rain_data['날짜'].dt.day
temp_rain_data.head(1)

          날짜  평균기온(℃)  최저기온(℃)  최고기온(℃)  강수량(mm) 기상조건     연  월  일
0 2022-07-01     26.6     21.9     30.9      0.0   맑음  2022  7  1

In [26]:
# 요일 추가
temp_rain_data['요일'] = temp_rain_data['날짜'].dt.weekday
temp_rain_data

            날짜  평균기온(℃)  최저기온(℃)  최고기온(℃)  강수량(mm)   기상조건     연  월   일  요일
0   2022-07-01     26.6     21.9     30.9      0.0     맑음  2022  7   1   4
1   2022-07-02     28.8     24.0     33.8      0.0  폭염/한파  2022  7   2   5
2   2022-07-03     29.3     24.4     34.2      0.0  폭염/한파  2022  7   3   6
3   2022-07-04     29.3     26.4     32.6      0.0     맑음  2022  7   4   0
4   2022-07-05     29.2     26.7     33.1      0.0  폭염/한파  2022  7   5   1
..         ...      ...      ...      ...      ...    ...   ... ..  ..  ..
411 2023-08-16     27.3     24.7     31.6      0.3   약한눈비  2023  8  16   2
412 2023-08-17     28.2     24.5     32.4      0.0     맑음  2023  8  17   3
413 2023-08-18     29.1     25.5     33.3      0.1  폭염/한파  2023  8  18   4
414 2023-08-19     29.1     26.4     33.6      0.0  폭염/한파  2023  8  19   5
415 2023-08-20     28.3     25.5     31.8      0.0     맑음  2023  8  20   6

[416 rows x 10 columns]

In [28]:
# 0~6번 인덱스 위치에 각 한글 요일 이름이 담긴 리스트
weekday_list = ['월', '화', '수', '목', '금', '토', '일']

# apply 함수로 숫자 -> 요일 이름으로 변환
temp_rain_data['요일'] = temp_rain_data.apply(lambda x : weekday_list[x['요일']], axis = 1)

temp_rain_data

            날짜  평균기온(℃)  최저기온(℃)  최고기온(℃)  강수량(mm)   기상조건     연  월   일 요일
0   2022-07-01     26.6     21.9     30.9      0.0     맑음  2022  7   1  금
1   2022-07-02     28.8     24.0     33.8      0.0  폭염/한파  2022  7   2  토
2   2022-07-03     29.3     24.4     34.2      0.0  폭염/한파  2022  7   3  일
3   2022-07-04     29.3     26.4     32.6      0.0     맑음  2022  7   4  월
4   2022-07-05     29.2     26.7     33.1      0.0  폭염/한파  2022  7   5  화
..         ...      ...      ...      ...      ...    ...   ... ..  .. ..
411 2023-08-16     27.3     24.7     31.6      0.3   약한눈비  2023  8  16  수
412 2023-08-17     28.2     24.5     32.4      0.0     맑음  2023  8  17  목
413 2023-08-18     29.1     25.5     33.3      0.1  폭염/한파  2023  8  18  금
414 2023-08-19     29.1     26.4     33.6      0.0  폭염/한파  2023  8  19  토
415 2023-08-20     28.3     25.5     31.8      0.0     맑음  2023  8  20  일

[416 rows x 10 columns]

In [29]:
# 날짜 컬럼 삭제
temp_rain_df = temp_rain_data.drop(['날짜'], axis=1).copy()
temp_rain_df

     평균기온(℃)  최저기온(℃)  최고기온(℃)  강수량(mm)   기상조건     연  월   일 요일
0       26.6     21.9     30.9      0.0     맑음  2022  7   1  금
1       28.8     24.0     33.8      0.0  폭염/한파  2022  7   2  토
2       29.3     24.4     34.2      0.0  폭염/한파  2022  7   3  일
3       29.3     26.4     32.6      0.0     맑음  2022  7   4  월
4       29.2     26.7     33.1      0.0  폭염/한파  2022  7   5  화
..       ...      ...      ...      ...    ...   ... ..  .. ..
411     27.3     24.7     31.6      0.3   약한눈비  2023  8  16  수
412     28.2     24.5     32.4      0.0     맑음  2023  8  17  목
413     29.1     25.5     33.3      0.1  폭염/한파  2023  8  18  금
414     29.1     26.4     33.6      0.0  폭염/한파  2023  8  19  토
415     28.3     25.5     31.8      0.0     맑음  2023  8  20  일

[416 rows x 9 columns]

In [30]:
# 컬럼 순서 바꾸기
temp_rain_df = temp_rain_df[['연', '월', '일', '요일', '기상조건', '평균기온(℃)', '최저기온(℃)', '최고기온(℃)', '강수량(mm)']]
temp_rain_df

        연  월   일 요일   기상조건  평균기온(℃)  최저기온(℃)  최고기온(℃)  강수량(mm)
0    2022  7   1  금     맑음     26.6     21.9     30.9      0.0
1    2022  7   2  토  폭염/한파     28.8     24.0     33.8      0.0
2    2022  7   3  일  폭염/한파     29.3     24.4     34.2      0.0
3    2022  7   4  월     맑음     29.3     26.4     32.6      0.0
4    2022  7   5  화  폭염/한파     29.2     26.7     33.1      0.0
..    ... ..  .. ..    ...      ...      ...      ...      ...
411  2023  8  16  수   약한눈비     27.3     24.7     31.6      0.3
412  2023  8  17  목     맑음     28.2     24.5     32.4      0.0
413  2023  8  18  금  폭염/한파     29.1     25.5     33.3      0.1
414  2023  8  19  토  폭염/한파     29.1     26.4     33.6      0.0
415  2023  8  20  일     맑음     28.3     25.5     31.8      0.0

[416 rows x 9 columns]

In [32]:
temp_rain_df.to_csv("1_3_날짜_요일_기상조건.csv")