### 파일 불러오기

In [1]:
import pandas as pd

mons = pd.read_csv("/content/역별월별비율_15_22.csv")
days = pd.read_csv("/content/역별요일별비율.csv")

In [2]:
# 엑셀 파일에서 모든 시트를 읽어서 딕셔너리 형태로 저장
excel_file = pd.ExcelFile('/content/2013년 혼잡도.xlsx')
sheet_names = excel_file.sheet_names  # 시트 이름 목록
sheet_names

/usr/local/lib/python3.10/dist-packages/openpyxl/reader/workbook.py:118: UserWarning: Print area cannot be set to Defined name: '일요일 상선'!$1:$126.
  warn(f"Print area cannot be set to Defined name: {defn.value}.")
/usr/local/lib/python3.10/dist-packages/openpyxl/reader/workbook.py:118: UserWarning: Print area cannot be set to Defined name: '일요일 하선'!$1:$126.
  warn(f"Print area cannot be set to Defined name: {defn.value}.")
/usr/local/lib/python3.10/dist-packages/openpyxl/reader/workbook.py:118: UserWarning: Print area cannot be set to Defined name: '토요일 상선'!$1:$126.
  warn(f"Print area cannot be set to Defined name: {defn.value}.")
/usr/local/lib/python3.10/dist-packages/openpyxl/reader/workbook.py:118: UserWarning: Print area cannot be set to Defined name: '토요일 하선'!$1:$126.
  warn(f"Print area cannot be set to Defined name: {defn.value}.")
/usr/local/lib/python3.10/dist-packages/openpyxl/reader/workbook.py:118: UserWarning: Print area cannot be set to Defined name: '평일 상선'!$1:$126.
  warn(f"Print area cannot be set to Defined name: {defn.value}.")
/usr/local/lib/python3.10/dist-packages/openpyxl/reader/workbook.py:118: UserWarning: Print area cannot be set to Defined name: '평일 하선'!$1:$126.
  warn(f"Print area cannot be set to Defined name: {defn.value}.")

['평일 상선', '평일 하선', '토요일 상선', '토요일 하선', '일요일 상선', '일요일 하선']

In [3]:
# 모든 시트의 데이터를 저장할 빈 리스트를 생성
all_dfs = []

for sheet_name in sheet_names:
    # 필요한 행부터 읽기 시작
    df = pd.read_excel(excel_file, sheet_name=sheet_name, header=2)

    # 불필요한 열 삭제
    df.dropna(axis=1, how='all', inplace=True)

    # 요일구분 컬럼 추가
    day_of_week = sheet_name.split()[-2]  # 시트 이름에서 요일 정보 추출
    df['요일구분'] = day_of_week

    # 상하구분 컬럼 추가 (상선 또는 하선)
    direction = '상선' if '상선' in sheet_name else '하선'
    df['상하구분'] = direction

    # 데이터프레임을 리스트에 추가
    all_dfs.append(df)

In [4]:
all_dfs

[      호선     역명  방향  5시대  6시대  7시대  8시대  9시대  10시대  11시대  ...  17시대  18시대  \
 0    1호선    서울역  상선   10   20   43   72   54    35    42  ...    33    54
 1    NaN     시청  상선   10   20   40   66   55    39    47  ...    41    72
 2    NaN     종각  상선   10   17   29   50   46    35    44  ...    45    79
 3    NaN   종로3가  상선   10   17   31   57   50    42    47  ...    54    96
 4    NaN   종로5가  상선   10   16   26   45   42    37    43  ...    57    97
 ..   ...    ...  ..  ...  ...  ...  ...  ...   ...   ...  ...   ...   ...
 118  NaN     이촌  상선   16   21   44   72   42    35    37  ...    40    44
 119  NaN     동작  상선   17   23   47   69   45    31    40  ...    42    44
 120  NaN  총신대입구  상선   18   26   51   75   42    32    40  ...    40    45
 121  NaN     사당  상선   19   24   51   70   42    32    38  ...    42    46
 122  NaN    남태령  상선   24   37  107  138   89    60    65  ...    71    95

      19시대  20시대  21시대  22시대  23시대  24시대  요일구분  상하구분
 0      42    25    29    26    15     4    평일    상선
 1      58    34    40    37    21     7    평일    상선
 2      63    40    53    51    27     6    평일    상선
 3      78    49    63    61    34     8    평일    상선
 4      82    52    64    65    35     8    평일    상선
 ..    ...   ...   ...   ...   ...   ...   ...   ...
 118    35    22    22    26    18     8    평일    상선
 119    35    21    24    25    19     9    평일    상선
 120    33    21    22    25    19     8    평일    상선
 121    35    23    22    26    21    14    평일    상선
 122    73    34    34    39    27    10    평일    상선

 [123 rows x 25 columns],
       호선     역명  방향  5시대  6시대  7시대  8시대  9시대  10시대  11시대  ...  17시대  18시대  \
 0    1호선    서울역  하선   10   16   30   37   22    23    23  ...    52    82
 1    NaN     시청  하선   13   18   35   46   27    26    27  ...    56    82
 2    NaN     종각  하선   16   24   55   74   41    36    36  ...    66    87
 3    NaN   종로3가  하선   18   27   63   93   51    41    38  ...    64    79
 4    NaN   종로5가  하선   22   31   74  110   57    48    44  ...    67    81
 ..   ...    ...  ..  ...  ...  ...  ...  ...   ...   ...  ...   ...   ...
 118  NaN     이촌  하선   43   16   26   35   23    25    25  ...    44    61
 119  NaN     동작  하선    0   20   26   37   24    26    27  ...    46    65
 120  NaN  총신대입구  하선    0   23   28   40   25    28    28  ...    44    59
 121  NaN     사당  하선   22   21   26   33   22    26    23  ...    39    56
 122  NaN    남태령  하선   22   33   48   67   43    48    43  ...    78   105

      19시대  20시대  21시대  22시대  23시대  24시대  요일구분  상하구분
 0      51    36    40    46    29     5    평일    하선
 1      52    37    43    47    29     2    평일    하선
 2      54    38    44    50    34     3    평일    하선
 3      48    31    33    35    24     3    평일    하선
 4      44    31    32    34    24     2    평일    하선
 ..    ...   ...   ...   ...   ...   ...   ...   ...
 118    47    38    38    48    42     9    평일    하선
 119    52    40    42    49    44     9    평일    하선
 120    50    38    40    47    41     8    평일    하선
 121    45    38    36    44    42     7    평일    하선
 122    89    66    67    80    70    20    평일    하선

 [123 rows x 25 columns],
       호선     역명  방향  5시대  6시대  7시대  8시대  9시대  10시대  11시대  ...  17시대  18시대  \
 0    1호선    서울역  상선   10   21   22   39   41    40    49  ...    47    41
 1    NaN     시청  상선   10   23   24   39   44    41    53  ...    56    50
 2    NaN     종각  상선   10   21   22   37   40    38    48  ...    55    51
 3    NaN   종로3가  상선   10   23   25   40   42    40    53  ...    67    58
 4    NaN   종로5가  상선    9   21   23   35   39    35    46  ...    66    59
 ..   ...    ...  ..  ...  ...  ...  ...  ...   ...   ...  ...   ...   ...
 118  NaN     이촌  상선   11   17   19   36   50    42    47  ...    47    47
 119  NaN     동작  상선   11   18   20   38   52    45    45  ...    47    46
 120  NaN  총신대입구  상선   21   16   22   41   52    45    46  ...    46    46
 121  NaN     사당  상선   18   15   21   38   52    45    45  ...    47    53
 122  NaN    남태령  상선   20   29   43   59   95    92    90  ...   109   124

      19시대  20시대  21시대  22시대  23시대  24시대  요일구분  상하구분
 0      29    23    26    25    15   6.0   토요일    상선
 1      37    31    34    33    21  19.0   토요일    상선
 2      40    37    43    45    29  12.0   토요일    상선
 3      46    43    48    51    32  13.0   토요일    상선
 4      47    43    49    54    32  13.0   토요일    상선
 ..    ...   ...   ...   ...   ...   ...   ...   ...
 118    26    24    24    27    36   NaN   토요일    상선
 119    25    23    24    26    36   NaN   토요일    상선
 120    24    24    23    27    36   NaN   토요일    상선
 121    25    24    25    31    38   NaN   토요일    상선
 122    52    42    37    40    52   NaN   토요일    상선

 [123 rows x 25 columns],
       호선     역명  방향  5시대  6시대  7시대  8시대  9시대  10시대  11시대  ...  17시대  18시대  \
 0    1호선    서울역  하선   14   15   15   22   27    30    33  ...    54    49
 1    NaN     시청  하선   21   20   18   27   33    34    36  ...    63    51
 2    NaN     종각  하선   29   24   22   35   42    45    48  ...    76    59
 3    NaN   종로3가  하선   29   26   23   38   47    49    51  ...    75    60
 4    NaN   종로5가  하선   29   29   27   50   55    56    58  ...    75    60
 ..   ...    ...  ..  ...  ...  ...  ...  ...   ...   ...  ...   ...   ...
 118  NaN     이촌  하선   41   15   15   23   31    29    30  ...    58    50
 119  NaN     동작  하선    0   19   16   23   33    31    32  ...    60    52
 120  NaN  총신대입구  하선    0   21   17   25   35    34    34  ...    57    51
 121  NaN     사당  하선   22   17   15   28   34    39    32  ...    51    46
 122  NaN    남태령  하선   22   34   30   44   57    78    59  ...   102    99

      19시대  20시대  21시대  22시대  23시대  24시대  요일구분  상하구분
 0      39    30    36    35    23     5   토요일    하선
 1      45    34    41    36    25     6   토요일    하선
 2      48    36    44    40    31     6   토요일    하선
 3      41    29    32    29    22     6   토요일    하선
 4      38    29    30    27    18     0   토요일    하선
 ..    ...   ...   ...   ...   ...   ...   ...   ...
 118    39    35    42    46    39     0   토요일    하선
 119    43    38    41    48    40     0   토요일    하선
 120    42    36    39    46    38     0   토요일    하선
 121    41    36    40    45    37     9   토요일    하선
 122    82    71    63    80    45    24   토요일    하선

 [123 rows x 25 columns],
       호선     역명  방향  5시대  6시대  7시대  8시대  9시대  10시대  11시대  ...  17시대  18시대  \
 0    1호선    서울역  상선    6   13   13   25   29    33    41  ...    35    29
 1    NaN     시청  상선    6   15   14   25   32    35    44  ...    43    36
 2    NaN     종각  상선    7   14   14   24   29    32    40  ...    45    40
 3    NaN   종로3가  상선    6   15   16   26   31    34    42  ...    52    46
 4    NaN   종로5가  상선    6   14   15   24   30    33    40  ...    51    46
 ..   ...    ...  ..  ...  ...  ...  ...  ...   ...   ...  ...   ...   ...
 118  NaN     이촌  상선    7   10   11   20   35    33    37  ...    36    37
 119  NaN     동작  상선    7   10   12   22   38    35    35  ...    36    38
 120  NaN  총신대입구  상선   12    9   12   23   38    35    35  ...    36    39
 121  NaN     사당  상선   11    9   12   22   37    34    35  ...    40    49
 122  NaN    남태령  상선   12   20   25   34   67    68    65  ...    99   127

      19시대  20시대  21시대  22시대  23시대  24시대  요일구분  상하구분
 0      25    21    23    21    12     4   일요일    상선
 1      28    27    29    26    15    11   일요일    상선
 2      33    35    36    34    19     8   일요일    상선
 3      39    40    40    39    21     8   일요일    상선
 4      40    39    42    41    22     8   일요일    상선
 ..    ...   ...   ...   ...   ...   ...   ...   ...
 118    22    22    21    21    25     0   일요일    상선
 119    21    21    21    20    25     0   일요일    상선
 120    21    22    21    21    23     0   일요일    상선
 121    23    23    21    24    23     0   일요일    상선
 122    49    42    34    32    19     0   일요일    상선

 [123 rows x 25 columns],
       호선     역명  방향  5시대  6시대  7시대  8시대  9시대  10시대  11시대  ...  17시대  18시대  \
 0    1호선    서울역  하선    9   10    8   13   21    22    24  ...    47    43
 1    NaN     시청  하선   13   12   10   15   24    25    27  ...    57    45
 2    NaN     종각  하선   18   14   12   20   30    34    36  ...    66    50
 3    NaN   종로3가  하선   16   15   13   22   33    36    39  ...    62    47
 4    NaN   종로5가  하선   15   16   15   29   38    41    44  ...    63    48
 ..   ...    ...  ..  ...  ...  ...  ...  ...   ...   ...  ...   ...   ...
 118  NaN     이촌  하선   30   11    8   14   24    26    22  ...    43    40
 119  NaN     동작  하선    0   13    9   14   25    28    24  ...    45    41
 120  NaN  총신대입구  하선    0   15   10   16   28    32    27  ...    41    39
 121  NaN     사당  하선   12   11    9   19   32    44    30  ...    35    34
 122  NaN    남태령  하선   12   22   17   31   52    89    55  ...    71    73

      19시대  20시대  21시대  22시대  23시대  24시대  요일구분  상하구분
 0      37    28    29    25    15     3   일요일    하선
 1      42    31    32    24    15     3   일요일    하선
 2      46    33    35    26    17     4   일요일    하선
 3      36    25    25    20    14     4   일요일    하선
 4      34    25    24    20    12     0   일요일    하선
 ..    ...   ...   ...   ...   ...   ...   ...   ...
 118    35    32    36    34    25     0   일요일    하선
 119    37    35    36    35    27     0   일요일    하선
 120    34    33    34    33    25     0   일요일    하선
 121    32    30    33    30    22     7   일요일    하선
 122    64    59    51    54    28    14   일요일    하선

 [123 rows x 25 columns]]

In [5]:
# 리스트에 있는 모든 데이터프레임을 합치기
df_13 = pd.concat(all_dfs, ignore_index=True)

In [6]:
df_13.info

<bound method DataFrame.info of       호선     역명  방향  5시대  6시대  7시대  8시대  9시대  10시대  11시대  ...  17시대  18시대  \
0    1호선    서울역  상선   10   20   43   72   54    35    42  ...    33    54
1    NaN     시청  상선   10   20   40   66   55    39    47  ...    41    72
2    NaN     종각  상선   10   17   29   50   46    35    44  ...    45    79
3    NaN   종로3가  상선   10   17   31   57   50    42    47  ...    54    96
4    NaN   종로5가  상선   10   16   26   45   42    37    43  ...    57    97
..   ...    ...  ..  ...  ...  ...  ...  ...   ...   ...  ...   ...   ...
733  NaN     이촌  하선   30   11    8   14   24    26    22  ...    43    40
734  NaN     동작  하선    0   13    9   14   25    28    24  ...    45    41
735  NaN  총신대입구  하선    0   15   10   16   28    32    27  ...    41    39
736  NaN     사당  하선   12   11    9   19   32    44    30  ...    35    34
737  NaN    남태령  하선   12   22   17   31   52    89    55  ...    71    73

     19시대  20시대  21시대  22시대  23시대  24시대  요일구분  상하구분
0      42    25    29    26    15   4.0    평일    상선
1      58    34    40    37    21   7.0    평일    상선
2      63    40    53    51    27   6.0    평일    상선
3      78    49    63    61    34   8.0    평일    상선
4      82    52    64    65    35   8.0    평일    상선
..    ...   ...   ...   ...   ...   ...   ...   ...
733    35    32    36    34    25   0.0   일요일    하선
734    37    35    36    35    27   0.0   일요일    하선
735    34    33    34    33    25   0.0   일요일    하선
736    32    30    33    30    22   7.0   일요일    하선
737    64    59    51    54    28  14.0   일요일    하선

[738 rows x 25 columns]>

In [7]:
# 시간대 컬럼 이름 변경
new_columns = {
    '5시대': '05시~06시', '6시대': '06시~07시', '7시대': '07시~08시', '8시대': '08시~09시', '9시대': '09시~10시',
    '10시대': '10시~11시', '11시대': '11시~12시', '12시대': '12시~13시', '13시대': '13시~14시', '14시대': '14시~15시',
    '15시대': '15시~16시', '16시대': '16시~17시', '17시대': '17시~18시', '18시대': '18시~19시', '19시대': '19시~20시',
    '20시대': '20시~21시', '21시대': '21시~22시', '22시대': '22시~23시', '23시대': '23시~24시', '24시대': '24시~01시'
}

df_13.rename(columns=new_columns, inplace=True)

In [8]:
# 컬럼 순서 변경
new_column_order = ['요일구분', '호선', '역명', '상하구분', '05시~06시', '06시~07시', '07시~08시', '08시~09시', '09시~10시', '10시~11시', '11시~12시',
                    '12시~13시', '13시~14시', '14시~15시', '15시~16시', '16시~17시', '17시~18시', '18시~19시', '19시~20시', '20시~21시',
                    '21시~22시', '22시~23시', '23시~24시', '24시~01시']

In [9]:
df_13 = df_13[new_column_order]

In [10]:
df_13.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 738 entries, 0 to 737
Data columns (total 24 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   요일구분     738 non-null    object
 1   호선       24 non-null     object
 2   역명       738 non-null    object
 3   상하구분     738 non-null    object
 4   05시~06시  738 non-null    int64
 5   06시~07시  738 non-null    int64
 6   07시~08시  738 non-null    int64
 7   08시~09시  738 non-null    int64
 8   09시~10시  738 non-null    int64
 9   10시~11시  738 non-null    int64
 10  11시~12시  738 non-null    int64
 11  12시~13시  738 non-null    int64
 12  13시~14시  738 non-null    int64
 13  14시~15시  738 non-null    int64
 14  15시~16시  738 non-null    int64
 15  16시~17시  738 non-null    int64
 16  17시~18시  738 non-null    int64
 17  18시~19시  738 non-null    int64
 18  19시~20시  738 non-null    int64
 19  20시~21시  738 non-null    int64
 20  21시~22시  738 non-null    int64
 21  22시~23시  738 non-null    int64
 22  23시~24시  738 non-null    int64
 23  24시~01시  625 non-null    float64
dtypes: float64(1), int64(19), object(4)
memory usage: 138.5+ KB

### 결측값 처리 (호선명 채우기)

In [11]:
# 비어있는 호선 값 채우기
for index, row in df_13.iterrows():
    if pd.isnull(row['호선']):  # 호선 값이 NULL인 경우
        df_13.at[index, '호선'] = df_13.at[index - 1, '호선']  # 직전 행의 호선 값 복사

In [12]:
df_13.head()

,요일구분,호선,역명,상하구분,05시~06시,06시~07시,07시~08시,08시~09시,09시~10시,10시~11시,...,15시~16시,16시~17시,17시~18시,18시~19시,19시~20시,20시~21시,21시~22시,22시~23시,23시~24시,24시~01시
0,평일,1호선,서울역,상선,10,20,43,72,54,35,...,33,34,33,54,42,25,29,26,15,4.0
1,평일,1호선,시청,상선,10,20,40,66,55,39,...,40,43,41,72,58,34,40,37,21,7.0
2,평일,1호선,종각,상선,10,17,29,50,46,35,...,44,45,45,79,63,40,53,51,27,6.0
3,평일,1호선,종로3가,상선,10,17,31,57,50,42,...,55,54,54,96,78,49,63,61,34,8.0
4,평일,1호선,종로5가,상선,10,16,26,45,42,37,...,53,53,57,97,82,52,64,65,35,8.0

### df_13 데이터 형식 수정

In [13]:
# 호선 문자열 수정
df_13['호선'] = df_13['호선'].str.extract('(\d+)').astype(int)

# 시간대 실수형으로 형식 바꾸기
time_columns = ['05시~06시', '06시~07시', '07시~08시', '08시~09시', '09시~10시',
                '10시~11시', '11시~12시', '12시~13시', '13시~14시', '14시~15시',
                '15시~16시', '16시~17시', '17시~18시', '18시~19시', '19시~20시',
                '20시~21시', '21시~22시', '22시~23시', '23시~24시', '24시~01시']

for col in time_columns:
    df_13[col] = df_13[col].astype('float64')

<ipython-input-13-5430ead4447a>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_13['호선'] = df_13['호선'].str.extract('(\d+)').astype(int)
<ipython-input-13-5430ead4447a>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_13[col] = df_13[col].astype('float64')

In [14]:
df_13.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 738 entries, 0 to 737
Data columns (total 24 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   요일구분     738 non-null    object
 1   호선       738 non-null    int64
 2   역명       738 non-null    object
 3   상하구분     738 non-null    object
 4   05시~06시  738 non-null    float64
 5   06시~07시  738 non-null    float64
 6   07시~08시  738 non-null    float64
 7   08시~09시  738 non-null    float64
 8   09시~10시  738 non-null    float64
 9   10시~11시  738 non-null    float64
 10  11시~12시  738 non-null    float64
 11  12시~13시  738 non-null    float64
 12  13시~14시  738 non-null    float64
 13  14시~15시  738 non-null    float64
 14  15시~16시  738 non-null    float64
 15  16시~17시  738 non-null    float64
 16  17시~18시  738 non-null    float64
 17  18시~19시  738 non-null    float64
 18  19시~20시  738 non-null    float64
 19  20시~21시  738 non-null    float64
 20  21시~22시  738 non-null    float64
 21  22시~23시  738 non-null    float64
 22  23시~24시  738 non-null    float64
 23  24시~01시  625 non-null    float64
dtypes: float64(20), int64(1), object(3)
memory usage: 138.5+ KB

In [15]:
df_13.isna().sum()

요일구분         0
호선           0
역명           0
상하구분         0
05시~06시      0
06시~07시      0
07시~08시      0
08시~09시      0
09시~10시      0
10시~11시      0
11시~12시      0
12시~13시      0
13시~14시      0
14시~15시      0
15시~16시      0
16시~17시      0
17시~18시      0
18시~19시      0
19시~20시      0
20시~21시      0
21시~22시      0
22시~23시      0
23시~24시      0
24시~01시    113
dtype: int64

### df_13 결측값 처리 (중앙값으로 채움)

In [16]:
df_13['24시~01시'].median()

0.0

In [17]:
df_13['24시~01시'].fillna(0, inplace=True)

<ipython-input-17-38fd60e5f3db>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_13['24시~01시'].fillna(0, inplace=True)

In [18]:
df_13.isna().sum()

요일구분       0
호선         0
역명         0
상하구분       0
05시~06시    0
06시~07시    0
07시~08시    0
08시~09시    0
09시~10시    0
10시~11시    0
11시~12시    0
12시~13시    0
13시~14시    0
14시~15시    0
15시~16시    0
16시~17시    0
17시~18시    0
18시~19시    0
19시~20시    0
20시~21시    0
21시~22시    0
22시~23시    0
23시~24시    0
24시~01시    0
dtype: int64

In [19]:
df_13.역명.value_counts()

서울역          12
시청           12
교대           12
동대문역사문화공원    12
을지3가         12
             ..
신대방           6
신림            6
봉천            6
서울대입구         6
남태령           6
Name: 역명, Length: 113, dtype: int64

### 혼잡도 구하기

In [20]:
melt_13 = pd.melt(df_13, id_vars=['요일구분', '호선', '역명', '상하구분'], var_name='시간대', value_name='값')
melt_13

      요일구분  호선     역명 상하구분      시간대     값
0       평일   1    서울역   상선  05시~06시  10.0
1       평일   1     시청   상선  05시~06시  10.0
2       평일   1     종각   상선  05시~06시  10.0
3       평일   1   종로3가   상선  05시~06시  10.0
4       평일   1   종로5가   상선  05시~06시  10.0
...    ...  ..    ...  ...      ...   ...
14755  일요일   4     이촌   하선  24시~01시   0.0
14756  일요일   4     동작   하선  24시~01시   0.0
14757  일요일   4  총신대입구   하선  24시~01시   0.0
14758  일요일   4     사당   하선  24시~01시   7.0
14759  일요일   4    남태령   하선  24시~01시  14.0

[14760 rows x 6 columns]

In [21]:
melt_13.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14760 entries, 0 to 14759
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   요일구분    14760 non-null  object
 1   호선      14760 non-null  int64
 2   역명      14760 non-null  object
 3   상하구분    14760 non-null  object
 4   시간대     14760 non-null  object
 5   값       14760 non-null  float64
dtypes: float64(1), int64(1), object(4)
memory usage: 692.0+ KB

In [22]:
mons.rename(columns={'호선명': '호선', '지하철역': '역명'}, inplace=True)

In [23]:
mons = mons[(mons['호선'] == '1호선') | (mons['호선'] == '2호선') | (mons['호선'] == '3호선') | (mons['호선'] == '4호선')]

In [24]:
mons.호선.value_counts

<bound method IndexOpsMixin.value_counts of 0       1호선
1       1호선
2       1호선
3       1호선
4       1호선
       ...
1747    4호선
1748    4호선
1749    4호선
1750    4호선
1751    4호선
Name: 호선, Length: 1752, dtype: object>

In [25]:
mons = mons.replace({'호선' : '1호선'}, '1')
mons = mons.replace({'호선' : '2호선'}, '2')
mons = mons.replace({'호선' : '3호선'}, '3')
mons = mons.replace({'호선' : '4호선'}, '4')

In [26]:
mons

     호선         역명  사용월        비율
0     1        동대문    1  0.954919
1     1        동대문    2  0.882286
2     1        동대문    3  1.052501
3     1        동대문    4  1.032322
4     1        동대문    5  1.080913
...  ..        ...  ...       ...
1747  4  회현(남대문시장)    8  0.947942
1748  4  회현(남대문시장)    9  0.941920
1749  4  회현(남대문시장)   10  1.053734
1750  4  회현(남대문시장)   11  1.051536
1751  4  회현(남대문시장)   12  1.065747

[1752 rows x 4 columns]

In [27]:
melt_13.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14760 entries, 0 to 14759
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   요일구분    14760 non-null  object
 1   호선      14760 non-null  int64
 2   역명      14760 non-null  object
 3   상하구분    14760 non-null  object
 4   시간대     14760 non-null  object
 5   값       14760 non-null  float64
dtypes: float64(1), int64(1), object(4)
memory usage: 692.0+ KB

In [28]:
melt_13['호선'] = melt_13['호선'].astype(str)
merged_df = melt_13.merge(mons, on=['호선', '역명'], how='inner')
merged_df

       요일구분 호선   역명 상하구분      시간대     값  사용월        비율
0        평일  1  서울역   상선  05시~06시  10.0    1  1.002597
1        평일  1  서울역   상선  05시~06시  10.0    2  0.919665
2        평일  1  서울역   상선  05시~06시  10.0    3  1.014560
3        평일  1  서울역   상선  05시~06시  10.0    4  0.990673
4        평일  1  서울역   상선  05시~06시  10.0    5  1.034015
...     ... ..  ...  ...      ...   ...  ...       ...
159835  일요일  4  남태령   하선  24시~01시  14.0    8  1.193308
159836  일요일  4  남태령   하선  24시~01시  14.0    9  1.096531
159837  일요일  4  남태령   하선  24시~01시  14.0   10  0.997312
159838  일요일  4  남태령   하선  24시~01시  14.0   11  1.014522
159839  일요일  4  남태령   하선  24시~01시  14.0   12  0.987340

[159840 rows x 8 columns]

In [29]:
merged_df['월혼잡도'] = merged_df['값'] * merged_df['비율']
merged_df

       요일구분 호선   역명 상하구분      시간대     값  사용월        비율       월혼잡도
0        평일  1  서울역   상선  05시~06시  10.0    1  1.002597  10.025967
1        평일  1  서울역   상선  05시~06시  10.0    2  0.919665   9.196647
2        평일  1  서울역   상선  05시~06시  10.0    3  1.014560  10.145602
3        평일  1  서울역   상선  05시~06시  10.0    4  0.990673   9.906731
4        평일  1  서울역   상선  05시~06시  10.0    5  1.034015  10.340150
...     ... ..  ...  ...      ...   ...  ...       ...        ...
159835  일요일  4  남태령   하선  24시~01시  14.0    8  1.193308  16.706309
159836  일요일  4  남태령   하선  24시~01시  14.0    9  1.096531  15.351438
159837  일요일  4  남태령   하선  24시~01시  14.0   10  0.997312  13.962369
159838  일요일  4  남태령   하선  24시~01시  14.0   11  1.014522  14.203314
159839  일요일  4  남태령   하선  24시~01시  14.0   12  0.987340  13.822761

[159840 rows x 9 columns]

In [30]:
merged_df.역명.value_counts()

서울역          2880
신설동          2880
교대           2880
충무로          2880
동대문역사문화공원    2880
             ...
구로디지털단지      1440
신대방          1440
신림           1440
봉천           1440
남태령          1440
Name: 역명, Length: 102, dtype: int64

In [31]:
days.head()

   호선   역명 요일        비율
0   1  동대문  금  1.061534
1   1  동대문  목  1.020850
2   1  동대문  수  1.026641
3   1  동대문  월  1.005251
4   1  동대문  일  0.873151

In [32]:
days.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1932 entries, 0 to 1931
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   호선      1932 non-null   int64
 1   역명      1932 non-null   object
 2   요일      1932 non-null   object
 3   비율      1904 non-null   float64
dtypes: float64(1), int64(1), object(2)
memory usage: 60.5+ KB

In [33]:
days.rename(columns={'요일': '요일구분'}, inplace=True)
days = days[(days['호선'] == 1) | (days['호선'] == 2) | (days['호선'] == 3) | (days['호선'] == 4)]
days

     호선         역명 요일구분        비율
0     1        동대문    금  1.061534
1     1        동대문    목  1.020850
2     1        동대문    수  1.026641
3     1        동대문    월  1.005251
4     1        동대문    일  0.873151
..   ..        ...  ...       ...
835   4  회현(남대문시장)    수  1.138622
836   4  회현(남대문시장)    월  1.091271
837   4  회현(남대문시장)    일  0.453112
838   4  회현(남대문시장)    토  0.888779
839   4  회현(남대문시장)    화  1.149940

[840 rows x 4 columns]

In [34]:
merged_df = merged_df.replace({'요일구분' : '일요일'}, '일')
merged_df = merged_df.replace({'요일구분' : '토요일'}, '토')
merged_df.요일구분.value_counts()

평일    53280
토     53280
일     53280
Name: 요일구분, dtype: int64

In [35]:
weekday = merged_df[merged_df['요일구분'] == '평일'].copy()
# weekday
weeks = ['월', '화', '수', '목', '금']
result_df = pd.concat([weekday.assign(요일구분=요일) for 요일 in weeks], ignore_index=True)
result_df

       요일구분 호선   역명 상하구분      시간대     값  사용월        비율       월혼잡도
0         월  1  서울역   상선  05시~06시  10.0    1  1.002597  10.025967
1         월  1  서울역   상선  05시~06시  10.0    2  0.919665   9.196647
2         월  1  서울역   상선  05시~06시  10.0    3  1.014560  10.145602
3         월  1  서울역   상선  05시~06시  10.0    4  0.990673   9.906731
4         월  1  서울역   상선  05시~06시  10.0    5  1.034015  10.340150
...     ... ..  ...  ...      ...   ...  ...       ...        ...
266395    금  4  남태령   하선  24시~01시  20.0    8  1.193308  23.866156
266396    금  4  남태령   하선  24시~01시  20.0    9  1.096531  21.930625
266397    금  4  남태령   하선  24시~01시  20.0   10  0.997312  19.946241
266398    금  4  남태령   하선  24시~01시  20.0   11  1.014522  20.290449
266399    금  4  남태령   하선  24시~01시  20.0   12  0.987340  19.746801

[266400 rows x 9 columns]

In [36]:
result_df.역명.value_counts()

서울역          4800
신설동          4800
교대           4800
충무로          4800
동대문역사문화공원    4800
             ...
구로디지털단지      2400
신대방          2400
신림           2400
봉천           2400
남태령          2400
Name: 역명, Length: 102, dtype: int64

In [37]:
fin = pd.concat([result_df, merged_df[merged_df['요일구분'].isin(['토', '일'])]], ignore_index=True)
fin.요일구분.value_counts()

월    53280
화    53280
수    53280
목    53280
금    53280
토    53280
일    53280
Name: 요일구분, dtype: int64

In [38]:
fin['호선'] = fin['호선'].astype(int)
merged_fin = fin.merge(days, on=['호선', '역명', '요일구분'], how='inner')
merged_fin

       요일구분  호선   역명 상하구분      시간대     값  사용월      비율_x       월혼잡도      비율_y
0         월   1  서울역   상선  05시~06시  10.0    1  1.002597  10.025967  1.055483
1         월   1  서울역   상선  05시~06시  10.0    2  0.919665   9.196647  1.055483
2         월   1  서울역   상선  05시~06시  10.0    3  1.014560  10.145602  1.055483
3         월   1  서울역   상선  05시~06시  10.0    4  0.990673   9.906731  1.055483
4         월   1  서울역   상선  05시~06시  10.0    5  1.034015  10.340150  1.055483
...     ...  ..  ...  ...      ...   ...  ...       ...        ...       ...
288955    일   4  남태령   하선  24시~01시  14.0    8  1.193308  16.706309  0.627717
288956    일   4  남태령   하선  24시~01시  14.0    9  1.096531  15.351438  0.627717
288957    일   4  남태령   하선  24시~01시  14.0   10  0.997312  13.962369  0.627717
288958    일   4  남태령   하선  24시~01시  14.0   11  1.014522  14.203314  0.627717
288959    일   4  남태령   하선  24시~01시  14.0   12  0.987340  13.822761  0.627717

[288960 rows x 10 columns]

In [39]:
merged_fin.역명.value_counts()

서울역        6720
동대문        6720
시청         6720
충무로        6720
신설동        6720
           ...
영등포구청      3360
문래         3360
신도림        3360
구로디지털단지    3360
남태령        3360
Name: 역명, Length: 79, dtype: int64

In [40]:
merged_fin['최종혼잡도'] = merged_fin['월혼잡도'] * merged_fin['비율_y']
merged_fin

,요일구분,호선,역명,상하구분,시간대,값,사용월,비율_x,월혼잡도,비율_y,최종혼잡도
0,월,1,서울역,상선,05시~06시,10.0,1,1.002597,10.025967,1.055483,10.582233
1,월,1,서울역,상선,05시~06시,10.0,2,0.919665,9.196647,1.055483,9.706901
2,월,1,서울역,상선,05시~06시,10.0,3,1.014560,10.145602,1.055483,10.708505
3,월,1,서울역,상선,05시~06시,10.0,4,0.990673,9.906731,1.055483,10.456381
4,월,1,서울역,상선,05시~06시,10.0,5,1.034015,10.340150,1.055483,10.913848
...,...,...,...,...,...,...,...,...,...,...,...
288955,일,4,남태령,하선,24시~01시,14.0,8,1.193308,16.706309,0.627717,10.486833
288956,일,4,남태령,하선,24시~01시,14.0,9,1.096531,15.351438,0.627717,9.636357
288957,일,4,남태령,하선,24시~01시,14.0,10,0.997312,13.962369,0.627717,8.764416
288958,일,4,남태령,하선,24시~01시,14.0,11,1.014522,14.203314,0.627717,8.915661
288959,일,4,남태령,하선,24시~01시,14.0,12,0.987340,13.822761,0.627717,8.676781

In [41]:
merged_fin.head(30)

,요일구분,호선,역명,상하구분,시간대,값,사용월,비율_x,월혼잡도,비율_y,최종혼잡도
0,월,1,서울역,상선,05시~06시,10.0,1,1.002597,10.025967,1.055483,10.582233
1,월,1,서울역,상선,05시~06시,10.0,2,0.919665,9.196647,1.055483,9.706901
2,월,1,서울역,상선,05시~06시,10.0,3,1.014560,10.145602,1.055483,10.708505
3,월,1,서울역,상선,05시~06시,10.0,4,0.990673,9.906731,1.055483,10.456381
4,월,1,서울역,상선,05시~06시,10.0,5,1.034015,10.340150,1.055483,10.913848
5,월,1,서울역,상선,05시~06시,10.0,6,0.943472,9.434721,1.055483,9.958183
6,월,1,서울역,상선,05시~06시,10.0,7,0.977291,9.772915,1.055483,10.315141
7,월,1,서울역,상선,05시~06시,10.0,8,0.984706,9.847056,1.055483,10.393395
8,월,1,서울역,상선,05시~06시,10.0,9,0.966094,9.660942,1.055483,10.196955
9,월,1,서울역,상선,05시~06시,10.0,10,1.049155,10.491548,1.055483,11.073646
10,월,1,서울역,상선,05시~06시,10.0,11,1.056237,10.562370,1.055483,11.148397
11,월,1,서울역,상선,05시~06시,10.0,12,1.061535,10.615352,1.055483,11.204318
12,월,1,서울역,하선,05시~06시,10.0,1,1.002597,10.025967,1.055483,10.582233
13,월,1,서울역,하선,05시~06시,10.0,2,0.919665,9.196647,1.055483,9.706901
14,월,1,서울역,하선,05시~06시,10.0,3,1.014560,10.145602,1.055483,10.708505
15,월,1,서울역,하선,05시~06시,10.0,4,0.990673,9.906731,1.055483,10.456381
16,월,1,서울역,하선,05시~06시,10.0,5,1.034015,10.340150,1.055483,10.913848
17,월,1,서울역,하선,05시~06시,10.0,6,0.943472,9.434721,1.055483,9.958183
18,월,1,서울역,하선,05시~06시,10.0,7,0.977291,9.772915,1.055483,10.315141
19,월,1,서울역,하선,05시~06시,10.0,8,0.984706,9.847056,1.055483,10.393395
20,월,1,서울역,하선,05시~06시,10.0,9,0.966094,9.660942,1.055483,10.196955
21,월,1,서울역,하선,05시~06시,10.0,10,1.049155,10.491548,1.055483,11.073646
22,월,1,서울역,하선,05시~06시,10.0,11,1.056237,10.562370,1.055483,11.148397
23,월,1,서울역,하선,05시~06시,10.0,12,1.061535,10.615352,1.055483,11.204318
24,월,1,서울역,상선,06시~07시,20.0,1,1.002597,20.051934,1.055483,21.164466
25,월,1,서울역,상선,06시~07시,20.0,2,0.919665,18.393295,1.055483,19.413801
26,월,1,서울역,상선,06시~07시,20.0,3,1.014560,20.291204,1.055483,21.417011
27,월,1,서울역,상선,06시~07시,20.0,4,0.990673,19.813461,1.055483,20.912762
28,월,1,서울역,상선,06시~07시,20.0,5,1.034015,20.680301,1.055483,21.827696
29,월,1,서울역,상선,06시~07시,20.0,6,0.943472,18.869442,1.055483,19.916366

### (해결필요) 충무로 최종 혼잡도 결측치 문제
-

In [42]:
merged_fin.isna().sum()

요일구분        0
호선          0
역명          0
상하구분        0
시간대         0
값           0
사용월         0
비율_x        0
월혼잡도        0
비율_y     3360
최종혼잡도    3360
dtype: int64

In [52]:
missing_ratio_y_info = merged_fin[merged_fin['비율_y'].isna()]
missing_congestion_info = merged_fin[merged_fin['최종혼잡도'].isna()]

print("비율_y 결측치 정보:")
print(missing_ratio_y_info[['호선', '역명']])

print("\n최종혼잡도 결측치 정보:")
print(missing_congestion_info[['호선', '역명']])

비율_y 결측치 정보:
        호선   역명
24480    3  충무로
24481    3  충무로
24482    3  충무로
24483    3  충무로
24484    3  충무로
...     ..  ...
256315   3  충무로
256316   3  충무로
256317   3  충무로
256318   3  충무로
256319   3  충무로

[3360 rows x 2 columns]

최종혼잡도 결측치 정보:
        호선   역명
24480    3  충무로
24481    3  충무로
24482    3  충무로
24483    3  충무로
24484    3  충무로
...     ..  ...
256315   3  충무로
256316   3  충무로
256317   3  충무로
256318   3  충무로
256319   3  충무로

[3360 rows x 2 columns]

In [56]:
merged_fin[merged_fin['역명'] == '충무로']

,요일구분,호선,역명,상하구분,시간대,값,사용월,비율_x,월혼잡도,비율_y,최종혼잡도
24480,월,3,충무로,상선,05시~06시,14.0,1,0.835628,11.698785,NaN,NaN
24481,월,3,충무로,상선,05시~06시,14.0,2,0.699595,9.794332,NaN,NaN
24482,월,3,충무로,상선,05시~06시,14.0,3,1.110931,15.553036,NaN,NaN
24483,월,3,충무로,상선,05시~06시,14.0,4,1.042915,14.600810,NaN,NaN
24484,월,3,충무로,상선,05시~06시,14.0,5,1.085020,15.190283,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
283195,일,4,충무로,하선,24시~01시,0.0,8,0.915850,0.000000,0.36757,0.0
283196,일,4,충무로,하선,24시~01시,0.0,9,0.983196,0.000000,0.36757,0.0
283197,일,4,충무로,하선,24시~01시,0.0,10,1.045387,0.000000,0.36757,0.0
283198,일,4,충무로,하선,24시~01시,0.0,11,1.073807,0.000000,0.36757,0.0
283199,일,4,충무로,하선,24시~01시,0.0,12,1.050466,0.000000,0.36757,0.0

In [54]:
missing_congestion_info.역명.value_counts()

충무로    3360
Name: 역명, dtype: int64

In [44]:
# merged_fin.to_csv("df_13_merged_fin.csv")